############################################################
# Configuration of external libraries -- not all are needed
############################################################

uname_O := $(shell sh -c 'uname -o 2>/dev/null || echo not')
uname := $(shell sh -c 'uname -o 2>/dev/null || echo not')

CYGWIN = 0
LINUX = 0
MAC_OS_X = 0
ifeq ($(uname_O),Cygwin)
	CYGWIN = 1
endif
ifeq ($(uname),Linux)
	LINUX = 1
endif
ifeq (OSTYPE,MacOSX)
	MAC_OS_X = 1
endif

#set the directory containing tinyxml 
HAVE_TINYXML=1
TINYXML = $(HOME)

# math package
#set the following item to zero if GSL is not present
HAVE_GSL=1
#set the following 3 items to zero if CLAPACK is not present
HAVE_CLAPACK=0
HAVE_LAPACK=0
HAVE_BLAS=0
CLAPACK_DIR = $(HOME)/CLAPACK
MATH_DEFINES += HAVE_GSL=$(HAVE_GSL) HAVE_CLAPACK=$(HAVE_CLAPACK) HAVE_LAPACK=$(HAVE_LAPACK) HAVE_BLAS=$(HAVE_BLAS)
ifeq ($(HAVE_CLAPACK),1)
  MATH_INCDIR += $(CLAPACK_DIR) $(CLAPACK_DIR)/F2CLIBS $(CLAPACK_DIR)/BLAS/WRAP
endif
ifeq ($(HAVE_GSL),1)
  MATH_INCDIR += $(GSL_DIR)
endif

## For Mac, use HAVE_IEEE_COMPARISONS
# comment out the following line if isinf,isnan,finite are not defined
# on your system
MATH_DEFINES+= HAVE_DECL_ISINF HAVE_DECL_ISNAN HAVE_DECL_FINITE
# uncomment the following if you want to use IEEE comparisons to test
# nan,inf,finite numbers
#MATH_DEFINES+= HAVE_IEEE_COMPARISONS

## Default Settings
# optimization package
HAVE_GLPK=1
HAVE_LP_SOLVE=0
HAVE_OPTPP=0
HAVE_QPOPT=0
HAVE_QUADPROGPP=0
#GLPK = $(HOME)/glpk-4.28
GLPK = /usr/include/glpk
LPSOLVE = ../../../lp_solve_5.5
OPT++ = $(HOME)/OPT++2.1
QUADPROGPP = $(HOME)/QuadProg++
QPOPT = $(HOME)/qpopt

## Mac Settings
#HAVE_GLPK=1
#HAVE_LP_SOLVE=0
#HAVE_OPTPP=1
#HAVE_QPOPT=0
#HAVE_QUADPROGPP=0
#GLPK = /opt/local
#LPSOLVE = /opt/local
#OPT++ = /opt/local
#QUADPROGPP = $(HOME)/QuadProg++
#QPOPT = $(HOME)/qpopt

OPTIMIZATION_DEFINES += HAVE_LP_SOLVE=$(HAVE_LP_SOLVE) HAVE_GLPK=$(HAVE_GLPK) HAVE_OPTPP=$(HAVE_OPTPP) HAVE_QUADPROGPP=$(HAVE_QUADPROGPP) HAVE_QPOPT=$(HAVE_QPOPT)
ifeq ($HAVE_LP_SOLVE,1)
  OPTIMIZATION_INCDIR += $(LPSOLVE)
endif
ifeq ($(HAVE_GLPK),1)
	ifeq ($(MAC_OS_X),1)
		OPTIMIZATION_INCDIR += $(GLPK)/include
	else
		OPTIMIZATION_INCDIR += $(GLPK)
	endif
endif
ifeq ($(HAVE_OPTPP),1)
  OPTIMIZATION_INCDIR += $(OPT++)/include $(OPT++)/newmat09
endif
ifeq ($(HAVE_QUADPROGPP),1)
  OPTIMIZATION_INCDIR += $(QUADPROGPP)
  OPTIMIZATION_EXTRAOBJS += $(QUADPROGPP)/QuadProg++.o
endif
ifeq ($(HAVE_QPOPT),1)
  OPTIMIZATION_INCDIR += $(QPOPT)/include $(CLAPACK_DIR)/F2CLIBS
endif
ifeq ($(HAVE_GLPK),1)
  OPTIMIZATION_EXTRAOBJS += optimization/$(OBJDIR)/glpk/*.o
endif

# GLdraw package
HAVE_GLUT=1
HAVE_GLUI=1
ifeq ($(MAC_OS_X),1)
	GLUT=/System/Library/Frameworks/GLUT.framework
	GLUI=/opt/local
else
	#GLUT= ../../glut-3.7
        GLUT= /usr/include/
	GLUI= $(HOME)/Code/glui-2.36/src
endif
GLDRAW_DEFINES += HAVE_GLUT=$(HAVE_GLUT) HAVE_GLUI=$(HAVE_GLUI) GLUT_DISABLE_ATEXIT_HACK
ifeq ($(HAVE_GLUT),1)
  GLDRAW_INCDIR += $(GLUT)/include
endif
ifeq ($(HAVE_GLUI),1)
	ifeq ($(MAC_OS_X),1)
		GLDRAW_INCDIR += $(GLUI)/include
	else
		GLDRAW_INCDIR += $(GLUI)/include/GL
	endif
endif

# geometry package
HAVE_LRS=0
HAVE_PQP=1
LRS = $(HOME)/lrslib-041
#PQP = $(HOME)/Code/PQP_v1.3
PQP = geometry/PQP
GEOMETRY_DEFINES += HAVE_LRS=$(HAVE_LRS)
ifeq ($(HAVE_LRS),1)
  GEOMETRY_EXTRAOBJS += $(LRS)/objs/*.o
endif
GEOMETRY_DEFINES += HAVE_PQP=$(HAVE_PQP)
ifeq ($(HAVE_PQP),1)
  GEOMETRY_EXTRAOBJS += $(PQP)/lib/*.o
  GEOMETRY_INCDIRS += ../$(PQP)/include
endif

# statistics package
ifeq ($(HAVE_GSL),1)
  STATISTICS_INCDIR += $(GSL_DIR)
endif


KRISLIBRARY_EXTRAOBJS = $(GEOMETRY_EXTRAOBJS) $(OPTIMIZATION_EXTRAOBJS) $(MATH_EXTRAOBJS)
