include ../Makefile.config
SRCS= $(wildcard *.cpp)
INCDIR= ../ $(OPTIMIZATION_INCDIR)
DEFINES= $(OPTIMIZATION_DEFINES)
LIBNAME= optimization
EXTRAOBJS= $(OPTIMIZATION_EXTRAOBJS)
include ../Makefile.template
