include ../Makefile.config
SRCS= $(wildcard *.cpp)
#SRCS= KDTree.cpp ConvexHull2D.cpp SegmentOverlay.cpp GridSubdivision.cpp MonotoneChain.cpp
INCDIR= ../ $(GEOMETRY_INCDIRS)
DEFINES= $(GEOMETRY_DEFINES)
LIBNAME= geometry
EXTRAOBJS= $(wildcard PQP/lib/*.o)
include ../Makefile.template
