include ../Makefile.config
SRCS= $(wildcard *.cpp)
INCDIR= ../ $(STATISTICS_INCDIRS)
DEFINES= $(STATISTICS_DEFINES)
LIBNAME= statistics
EXTRAOBJS= $(STATISTICS_EXTRAOBJS)
include ../Makefile.template
